apiVersion : apps/v1beta1
kind: Deployment
metadata:
  name: lkkwanggateway 
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: lkkwanggateway 
    spec:
      containers:
        - name: lkkwanggateway 
          image: admin22acr.azurecr.io/lkkwanggateway
          ports:
          - containerPort: 8080